openapi: 3.0.0
info:
  title: ADA Markets API
  description: API for ADA Markets
  version: 1.0.0

servers:
  - url: https://api.ada-markets.com

paths:
  /aggregate:
    post:
      summary: Get Aggregate Data
      description: Returns aggregate market data based on the specified parameters.
      operationId: getAggregateData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sellCoin:
                  type: object
                  properties:
                    policyId:
                      type: string
                    nameHex:
                      type: string
                sellAmount:
                  type: number
                buyCoin:
                  type: object
                  properties:
                    policyId:
                      type: string
                    nameHex:
                      type: string
                slippage:
                  type: number
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  aggregateDetails:
                    type: object
                    properties:
                      estimatedReceive:
                        type: number
                      dexInfo:
                        type: array
                        items:
                          type: object
                          properties:
                            dexName:
                              type: string
                            price:
                              type: number
                            receiveAmount:
                              type: number
                            minimumReceive:
                              type: string
                              format: bigint
                            estimatedReceive:
                              type: string
                            priceImpactPercent:
                              type: number
                            swapFees:
                              type: array
                              items:
                                $ref: '#/components/schemas/SwapFee'
                            splitPercent:
                              type: number
                            sellAmount:
                              type: number
                  txCbor:
                    type: object

components:
  schemas:
    SwapFee:
      type: object
      properties:
        feeType:
          type: string
        amount:
          type: number
