openapi: 3.0.0
info:
  title: Ada Markets APIs
  version: 1.0.0
paths:
  /api/v0/aggregate:
    post:
      summary: Aggregate request for selling and buying coins
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AggregateRequest'
      responses:
        '200':
          description: Successfully processed the aggregate request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregateResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregateErrorResponse'
        '429':
          description: Too many requests

  /api/v0/chart/history:
    post:
      summary: Get historical chart data
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartDataRequest'
      responses:
        '200':
          description: Successfully retrieved historical chart data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChartDataResponse'
        '400':
          description: Invalid request
        '429':
          description: Too many requests

  /api/v0/coins/all:
    get:
      summary: Get all coins data
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved coins data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoinsResponse'
        '400':
          description: Invalid request
        '429':
          description: Too many requests

  /api/v0/latestprice:
    post:
      summary: Get latest price for a token pair
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LatestPriceRequest'
      responses:
        '200':
          description: Successfully retrieved latest price
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestPriceResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestPriceErrorResponse'
        '429':
          description: Too many requests

  /api/v0/latestprice/batch:
    post:
      summary: Get latest prices for multiple token pairs
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchLatestPriceRequest'
      responses:
        '200':
          description: Successfully retrieved batch prices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchLatestPriceResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestPriceErrorResponse'
        '429':
          description: Too many requests

  /api/swaps/myswaps:
    get:
      summary: Get user's swaps
      parameters:
        - in: query
          name: senderpubkeyhash
          required: true
          schema:
            type: string
          description: Sender's public key hash
        - in: query
          name: address
          required: true
          schema:
            type: string
          description: Wallet address
      responses:
        '200':
          description: Successfully retrieved user's swaps
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SwapResponse'
        '400':
          description: Invalid request

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AggregateRequest:
      type: object
      properties:
        sellCoin:
          $ref: '#/components/schemas/Asset'
        sellAmount:
          type: number
          description: Amount of the coin to sell
        buyCoin:
          $ref: '#/components/schemas/Asset'
        slippage:
          type: number
          description: Acceptable slippage for the transaction
        walletAddress:
          type: string
          description: Wallet address of the user
        additionalFees:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalFee'
        buildTx:
          type: boolean
          description: Whether to build the transaction
      required:
        - sellCoin
        - sellAmount
        - buyCoin
        - slippage
        - walletAddress
        - additionalFees
        - buildTx

    AggregateResponse:
      type: object
      properties:
        aggregateDetails:
          type: object
          properties:
            estimatedReceive:
              type: number
              description: Estimated amount to receive
            dexInfo:
              type: array
              items:
                $ref: '#/components/schemas/DexInfo'
            aggregatorFee:
              type: array
              items:
                $ref: '#/components/schemas/SwapFee'
        txCbor:
          type: string
          description: Transaction CBOR

    AggregateErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: number
              description: Error code
            message:
              type: string
              description: Error message
            details:
              type: string
              description: Detailed description of the error
      required:
        - error

    DexInfo:
      type: object
      properties:
        dexName:
          type: string
          description: Name of the decentralized exchange
        price:
          type: number
          description: Price of the asset
        minimumReceive:
          type: number
          description: Minimum amount to receive
        estimatedReceive:
          type: number
          description: Estimated amount to receive
        priceImpactPercent:
          type: number
          description: Price impact percentage
        swapFees:
          type: array
          items:
            $ref: '#/components/schemas/SwapFee'
        splitPercent:
          type: number
          description: Split percentage
        sellAmount:
          type: number
          description: Amount of the asset to sell

    SwapFee:
      type: object
      properties:
        id:
          type: string
          description: ID of the swap fee
        title:
          type: string
          description: Title of the swap fee
        description:
          type: string
          description: Description of the swap fee
        value:
          type: string
          format: bigint
          description: Value of the swap fee
        isReturned:
          type: boolean
          description: Whether the fee is returned

    ChartDataRequest:
      type: object
      properties:
        coinA:
          $ref: '#/components/schemas/Asset'
        coinB:
          $ref: '#/components/schemas/Asset'
        symbol:
          type: string
          description: Symbol representing the coin pair
        resolution:
          type: string
          description: Resolution of the chart data
        from:
          type: integer
          format: int64
          description: Start timestamp for the historical data
        to:
          type: integer
          format: int64
          description: End timestamp for the historical data
        countback:
          type: integer
          description: Number of data points to count back from the 'to' timestamp
      required:
        - coinA
        - coinB
        - symbol
        - resolution
        - from
        - to

    Asset:
      type: object
      properties:
        policyId:
          type: string
          description: Policy ID of the asset
        nameHex:
          type: string
          description: Name of the asset in hexadecimal
        decimals:
          type: integer
          description: Number of decimal places for the asset
      required:
        - policyId
        - nameHex

    AdditionalFee:
      type: object
      properties:
        title:
          type: string
          description: Title of the additional fee
        description:
          type: string
          description: Description of the additional fee
        walletAddress:
          type: string
          description: Wallet address for the fee
        value:
          type: string
          format: bigint
          description: Value of the additional fee
        isReturned:
          type: boolean
          description: Whether the fee is returned
      required:
        - title
        - description
        - walletAddress
        - value

    ChartDataResponse:
      type: object
      properties:
        time:
          type: string
          description: Time of the data point
        open:
          type: number
          description: Opening price
        high:
          type: number
          description: Highest price
        low:
          type: number
          description: Lowest price
        close:
          type: number
          description: Closing price
      required:
        - time
        - open
        - high
        - low
        - close

    CoinsResponse:
      type: object
      properties:
        title:
          type: string
          description: Title of the coin
        project:
          type: string
          description: Project associated with the coin
        img:
          type: string
          description: Image URL of the coin
        policyId:
          type: string
          description: Policy ID of the coin
        nameHex:
          type: string
          description: Name of the coin in hexadecimal
        decimals:
          type: number
          description: Number of decimal places for the coin
        quantity:
          type: number
          description: Quantity of the coin
        category:
          type: string
          description: Category of the coin
        website:
          type: string
          description: Website of the project
        twitter:
          type: string
          description: Twitter handle of the project
        tradableCoins:
          type: array
          items:
            $ref: '#/components/schemas/Asset'
        verified:
          type: boolean
          description: Whether the coin is verified
      required:
        - title
        - project
        - policyId
        - nameHex
        - decimals
        - quantity
        - tradableCoins

    LatestPriceRequest:
      type: object
      properties:
        tokenA:
          $ref: '#/components/schemas/Asset'
        tokenB:
          $ref: '#/components/schemas/Asset'
        resetCache:
          type: boolean
          description: Whether to reset the cache for this request
          default: false
      required:
        - tokenA
        - tokenB

    LatestPriceResponse:
      type: object
      properties:
        price:
          type: number
          description: The latest price for the token pair
      required:
        - price

    BatchLatestPriceRequest:
      type: object
      properties:
        pairs:
          type: array
          items:
            $ref: '#/components/schemas/TokenPair'
          maxItems: 50
          description: Array of token pairs to get prices for
      required:
        - pairs

    TokenPair:
      type: object
      properties:
        tokenA:
          $ref: '#/components/schemas/Asset'
        tokenB:
          $ref: '#/components/schemas/Asset'
      required:
        - tokenA
        - tokenB

    PriceResult:
      type: object
      properties:
        tokenA:
          $ref: '#/components/schemas/Asset'
        tokenB:
          $ref: '#/components/schemas/Asset'
        price:
          type: number
          nullable: true
          description: The price for this token pair
        status:
          type: string
          enum: [success, error]
          description: Status of the price fetch
        error:
          type: string
          description: Error message if status is error
      required:
        - tokenA
        - tokenB
        - status

    BatchLatestPriceResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/PriceResult'
      required:
        - results

    LatestPriceErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: number
              description: Error code
            message:
              type: string
              description: Error message
            details:
              type: string
              description: Detailed error description
          required:
            - code
            - message
            - details
      required:
        - error

    SwapResponse:
      type: object
      properties:
        txHash:
          type: string
          description: Transaction hash of the swap
        timestamp:
          type: string
          format: date-time
          description: Time when the swap occurred
        status:
          type: string
          enum: [pending, completed, failed]
          description: Status of the swap
        sellToken:
          $ref: '#/components/schemas/Asset'
        buyToken:
          $ref: '#/components/schemas/Asset'
        sellAmount:
          type: string
          description: Amount of tokens sold
        buyAmount:
          type: string
          description: Amount of tokens bought
      required:
        - txHash
        - timestamp
        - status
        - sellToken
        - buyToken
        - sellAmount
        - buyAmount